version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  worker:
    build:
      context: ../backend/
      dockerfile: ../backend/docker/Dockerfile.worker
    volumes:
      - /tmp/secret-volume:/etc/secret-volume
    privileged: true
    #entrypoint: celery
    command: ./docker/entrypoint-worker.sh
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis/0
      BUCKET_NAME: galatea
      #PYTHONPATH: /data
    depends_on:
      - redis
      - app
  flower:
    build:
      context: ../backend
      dockerfile: ../backend/docker/Dockerfile.flower
    command: celery -A worker.tasks flower
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis/0
      FLOWER_UNAUTHENTICATED_API: "true"
    volumes:
      - /tmp/secret-volume:/etc/secret-volume
    depends_on:
      - worker
      - redis
  app:
    build:
      context: ../backend
      dockerfile: ../backend/docker/Dockerfile
    volumes:
      - /tmp/secret-volume:/etc/secret-volume
    privileged: true
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis/0
      BUCKET_NAME: galatea
      AUTH0_DOMAIN: dev-xedas2iasb2dv6bb.us.auth0.com
      AUTH0_AUDIENCE: https://galatea-backend/
      #TEST_ENV: "yes"
      DEV: "true"
      PYTHONUNBUFFERED: "TRUE"
      DJANGO_SETTINGS_MODULE: "galatea.settings"
    ports:
      - 8000:8000
    command:
      - "/app/docker/entrypoint-dev.sh"
