FROM node:20-bookworm-slim

RUN apt update
RUN apt install -y python3 python3-pip libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

RUN pip install pytest --break-system-packages

WORKDIR /app

COPY frontend/package.json . 

RUN npm install

COPY frontend .

COPY .github/run_tests.sh run_tests.sh

COPY backend backend

ENV CYPRESS_BASE_URL="http://localhost:5173"

ENTRYPOINT [ "./run_tests.sh" ]