name: Dev build and test
on:
  push:
    branches:
      - "*"
      - "!main"

permissions:
  contents: "read"
  id-token: "write"

#Based on https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
#and https://cloud.google.com/blog/products/devops-sre/using-github-actions-with-google-cloud-deploy

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: authenticate to google cloud
        id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GCP_KEY}} | base64 -d"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "galatea-39660"

      - name: "Docker auth"
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up creds
        run: |
          mkdir /tmp/secret-volume
          echo "${{ secrets.GCP_KEY }}" | base64 -d > /tmp/secret-volume/sa-dev.json
        shell: bash

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ".github/docker-compose.ci.yml"
          up-flags: "--build"
        env:
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}

      - name: Run tests
        run: |
          mkdir /tmp/cypress; mkdir /tmp/cypress/videos; mkdir /tmp/logs
          docker build . -f .github/Dockerfile.tests -t tests
          docker run --network github_default -v /tmp/cypress/videos:/cypress/videos tests

            - name: Build and push Docker image - api
        if: steps.filter.outputs.backend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/docker/Dockerfile
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/galatea-396601/galatea/api:${SHORT_SHA}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image - worker
        if: steps.filter.outputs.backend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/docker/Dockerfile.worker
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/galatea-396601/galatea/worker:${SHORT_SHA}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save tag name to file
        run: echo ${SHORT_SHA} > /tmp/tag

      - name: Archive tag name
        uses: actions/upload-artifact@v3
        with:
          name: current-tag
          path: /tmp/tag

      - name: Print logs
        if: always()
        run: |
          docker-compose -f .github/docker-compose.ci.yml logs

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: /tmp/cypress/videos
