name: Dev build and test
on:
  push:
    branches:
      - "*"
      - "!main"

permissions:
  contents: "read"
  id-token: "write"

#Based on https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
#and https://cloud.google.com/blog/products/devops-sre/using-github-actions-with-google-cloud-deploy

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      #This step is for checking which files have changed
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend'
            backend:
              - 'backend'

      - name: authenticate to google cloud
        id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GCP_KEY}} | base64 -d"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "galatea-39660"

      - name: "Docker auth"
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up creds
        run: |
          mkdir /tmp/secret-volume
          echo "${{ secrets.GCP_KEY }}" | base64 -d > /tmp/secret-volume/cabana-dev-388204-ae3495fa8567.json
        shell: bash

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ".github/docker-compose.ci.yml"
          up-flags: "--build"
        env:
          OAUTH_CLIENT_ID: ${{secrets.OAUTH_CLIENT_ID}}
          OAUTH_SECRET: ${{secrets.OAUTH_SECRET}}

      - name: Run tests
        run: |
          mkdir /tmp/cypress; mkdir /tmp/cypress/videos; mkdir /tmp/logs
          docker build . -f .github/Dockerfile.tests -t tests
          docker run --network docker_default -v /tmp/cypress/videos:/cypress/videos tests

      - name: Print logs
        if: always()
        run: |
          docker-compose -f .github/docker-compose.ci.yml logs

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: /tmp/cypress/videos
