name: prod release
on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

#Based on https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
#and https://cloud.google.com/blog/products/devops-sre/using-github-actions-with-google-cloud-deploy

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      #This step is for checking which files have changed
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

      - name: authenticate to google cloud
        id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GCP_KEY}} | base64 -d"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "galatea-396601"

      - name: "Docker auth"
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: galatea-396601-gke
          location: australia-southeast1-a
          credentials: ${{secrets.GCP_KEY}} | base64 -d

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up creds
        run: |
          mkdir /tmp/secret-volume
          echo "${{ secrets.GCP_KEY }}" | base64 -d > /tmp/secret-volume/sa-dev.json
        shell: bash

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ".github/docker-compose.ci.yml"
          up-flags: "--build"
        env:
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}

      - name: Run tests
        run: |
          mkdir /tmp/cypress; mkdir /tmp/cypress/videos; mkdir /tmp/logs
          docker build . -f .github/Dockerfile.tests -t tests
          docker run --network github_default -v /tmp/cypress/videos:/cypress/videos tests

      - name: Print logs
        if: always()
        run: docker-compose -f .github/docker-compose.ci.yml logs

      - name: Build and push Docker image - api
        if: steps.filter.outputs.backend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/galatea-396601/galatea/api:latest
            australia-southeast1-docker.pkg.dev/galatea-396601/galatea/api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image - worker
        if: steps.filter.outputs.backend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile.worker
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/galatea-396601/galatea/worker:latest
            australia-southeast1-docker.pkg.dev/galatea-396601/galatea/worker:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #Based on https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine
      - name: Deploy
        run: |-
          yarn --cwd frontend install
          yarn --cwd frontend build
          gsutil -m rsync -r -c -d frontend/dist gs://galatea-static-website-bucket/
          kubectl rollout restart deployment/api
          kubectl rollout restart deployment/worker
